(defproject ("clpom")
  (plugin #'lisp-project)
  (define :version "2.0.0")
  (define :description "Basic Project Object Model management")
  (define :dependencies (list :lisp-unit :cl-ansi-text :cl-json :split-sequence :drakma :hunchentoot))
  (requires :task "update" :the-dependency "clean"))
